### ISSUE TITLE
ShortKey for the selection mode (Alt + Z)

### ISSUE THREAD

**Issue by Cryton1000** [joao-carloto/FireRobot#57]
I would love to have a shortkey for the selection mode to turn it on and off. Could that be something?

**Comment by joao-carloto** [comment]
This was badly implemented. It should now work without the need of toggling select mode on once with the button. Fix available on next release.

**Comment by joao-carloto** [comment]
Ctrl + Alt + S wasn't working in Linux (not sure why).
Changed it to Alt + Z (which is easier to use anyway).
